//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelatesTo
    {
        public string SeriesPrimary { get; set; }
        public string SeriesSecondary { get; set; }
        public Nullable<double> CorrelationScore { get; set; }
    
        public virtual Metric Metric { get; set; }
        public virtual Metric Metric1 { get; set; }
    }
}
