//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        public string CountryCode { get; set; }
        public string IndicatorCode { get; set; }
        public int Year { get; set; }
        public double Value { get; set; }
        public string CollectionMethodByYear { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Metric Metric { get; set; }
    }
}
