//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metric()
        {
            this.CollectedThroughs = new HashSet<CollectedThrough>();
            this.CorrelatesToes = new HashSet<CorrelatesTo>();
            this.CorrelatesToes1 = new HashSet<CorrelatesTo>();
            this.Footnotes = new HashSet<Footnote>();
            this.Indicators = new HashSet<Indicator>();
            this.MetricAggregations = new HashSet<MetricAggregation>();
            this.MetricDefinitions = new HashSet<MetricDefinition>();
        }
    
        public string SeriesCode { get; set; }
        public string Topic { get; set; }
        public string IndicatorName { get; set; }
        public string ShortDefinition { get; set; }
        public string LongDefinition { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Periodicity { get; set; }
        public string BasePeriod { get; set; }
        public string OtherNotes { get; set; }
        public string AggregationMethod { get; set; }
        public string LimitationsAndExceptions { get; set; }
        public string NotesFromOriginalSource { get; set; }
        public string GeneralComments { get; set; }
        public string Source { get; set; }
        public string StatisticalConceptAndMethodology { get; set; }
        public string DevelopmentRelevance { get; set; }
        public string RelatedSourceLinks { get; set; }
        public string OtherWebLinks { get; set; }
        public string RelatedIndicators { get; set; }
        public string LicenseType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectedThrough> CollectedThroughs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelatesTo> CorrelatesToes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelatesTo> CorrelatesToes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Footnote> Footnotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicator> Indicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetricAggregation> MetricAggregations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetricDefinition> MetricDefinitions { get; set; }
    }
}
