//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricAggregation
    {
        public string PeerGroup { get; set; }
        public string SeriesCode { get; set; }
        public int Year { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> P5 { get; set; }
        public Nullable<double> P10 { get; set; }
        public Nullable<double> P25 { get; set; }
        public Nullable<double> P50 { get; set; }
        public Nullable<double> P75 { get; set; }
        public Nullable<double> P90 { get; set; }
        public Nullable<double> P95 { get; set; }
    
        public virtual Metric Metric { get; set; }
    }
}
