//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricDefinition
    {
        public string Seriescode { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
    
        public virtual Metric Metric { get; set; }
    }
}
