//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMetricFactsAndStat
    {
        public string CountryCode { get; set; }
        public string IndicatorCode { get; set; }
        public string Topic { get; set; }
        public string IndicatorName { get; set; }
        public string UnitOfMeasure { get; set; }
        public string OtherNotes { get; set; }
        public string AggregationMethod { get; set; }
        public string LimitationsAndExceptions { get; set; }
        public int Year { get; set; }
        public double Value { get; set; }
        public Nullable<double> p5 { get; set; }
        public Nullable<double> p10 { get; set; }
        public Nullable<double> p25 { get; set; }
        public Nullable<double> p50 { get; set; }
        public Nullable<double> p75 { get; set; }
        public Nullable<double> p90 { get; set; }
        public Nullable<double> p95 { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<int> Size { get; set; }
        public int ranking { get; set; }
        public string CollectionMethodByYear { get; set; }
    }
}
